<!DOCTYPE html>
<html>
<head>
    <title>VZeta Web</title>
</head>
<body>
    <h1>¡Despliegue Exitoso en VZeta!</h1>
    <p>Esta aplicación está corriendo dentro de un contenedor Docker en AWS.</p>
</body>
</html>
